### ISSUE TITLE
API don't scale well

### ISSUE THREAD

**Issue by tibitoth** [mrlacey/UwpDesignTimeData#1]
My first thought is that the API is not flexible enough and hard to extend with custom properties. I will be thinking about it and will come back to this issue.

**Comment by tibitoth** [comment]
@mrlacey I have a working POC for custom control and any dependency property support.

The API would be the following where we can easily utilize the UWP's Style mechanizm:

```xaml
<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <StackPanel>
        <TextBlock Text="Runtime">
            <local:DesignTimeStyle.DesignTimeValues>
                <Style TargetType="TextBlock">
                    <Setter Property="Text" Value="DesignTime" />
                </Style>
            </local:DesignTimeStyle.DesignTimeValues>
        </TextBlock>

        <local:MyUserControl CustomProperty="Runtime">
            <local:DesignTimeStyle.DesignTimeValues>
                <Style TargetType="local:MyUserControl">
                    <Setter Property="CustomProperty" Value="DesignTime" />
                </Style>
            </local:DesignTimeStyle.DesignTimeValues>
        </local:MyUserControl>
    </StackPanel>
</Page>
```

The POC implementation is the following:

```C#
public static class DesignTimeStyle
    {
        public static void SetDesignTimeValues(UIElement element, Style value)
        {
            element.SetValue(DesignTimeValuesProperty, value);
        }

        public static Style GetDesignTimeValues(UIElement element)
        {
            return (Style)element.GetValue(DesignTimeValuesProperty);
        }

        public static readonly DependencyProperty DesignTimeValuesProperty =
            DependencyProperty.RegisterAttached(
                "DesignTimeValues",
                typeof(Style),
                typeof(DesignTimeStyle),
                new PropertyMetadata(null, OnDesignTimeValuesPropertyChanged));

        private static void OnDesignTimeValuesPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var style = e.NewValue as Style;
            if (style == null) return;

            if (DesignMode.DesignModeEnabled)
            {
                if (style.TargetType.IsAssignableFrom(d.GetType()))
                {
                    foreach (Setter setter in style.Setters)
                    {
                        d.SetValue(setter.Property, setter.Value);
                    }
                }
            }
        }
    }
```

If you are sattisfied I can open a pull request to support this scenario. Many people would love that.

**Comment by mrlacey** [comment]
I have questions:

- What is the current implementation "not flexible enough" for?
- I know it can't do everything, but that wasn't the goal. What specific properties do you want to set with different values that are shown in the designer?

I'm treating this project as a temporary solution until (hopefully) the equivalent functionality that exists for Xamarin.Forms comes to UWP. This is why I've used attached properties. This is so that, hopefully, once fully supported anything that uses this can be converted by replacing '`dt:DesignTime.`' with '`d:`'. Using your extended style syntax means more of a change would be required and adding support for more properties than the official solution is likely to do.  (I'm already covering more than the XF implementation does and more than I expect any built-in future UWP implementation to include. I did this because I was trying to cover all the properties I'd like to see have support. If starting again now, I'd probably avoid supporting things I don't expect to have official support to avoid breaking people in the future.)

All-in-all, you've got a nice way of showing how values in the designer could be modified for any property. What I don't see is what value this has. What other properties do you want to be different in the designer, and why?
Having recently been exposed to some discussion about the perceived verbosity of XAML, I don't think that setting everything with a `Style` is something that will be popular. I rarely see people prefer the longer form of writing something when a shorter version is available.
